spring:
  application:
    name: product-data-service
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_lab_manager?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
#server:
#  port: 8080
#  context-path: /demo-api
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.how2j.springcloud.pojo
#info:
#  appName: ${spring.application.name}
#  appDesc: 'Sancho Application Test'
#  groupId: '@project.groupId@'
#  artifactId: '@project.artifactId@'
#  version: '@project.version@'
#  license: GPL2
