spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/HONGXUWAN/springcloudConfig
          search-paths: respo
          username: 954335800@qq.com
          password: 320039690101wan
          ignore-local-ssh-settings: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/