spring:
  application:
    name:  product-view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#feign.hystrix.enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/